app = "arena-server-fresh-02240816"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.server"

[processes]
  app = "node apps/server/dist/apps/server/src/index.js"

[http_service]
  processes = ["app"]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
